openapi: 3.0.1
info:
  version: 1.0.0
  title: API documenations using Swagger
  description: Sample project to generates API swagger documentaion using multi file.
  contact:
    email: qau.aliuppal@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
schemes: [http, https]
host: localhost:400
basePath: /api/v1
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml